config/routes.rb
Lokusapp::Application.routes.draw do


  resources :devices do
    collection do
      get :new_point
      get :list_own_devices
    end


    member do

      get :new_point1
    end

  end

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  resources :home do


  end


  resources :faq do

  end

  resources :cart do

  end

  resources :item do

  end

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'loginpost'
        get 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end

      resources :users do
        collection do
          get :register_user
          post :register_user

        end
      end

      resources :locations do
        collection do
          get :add_location
          post :add_location

          get :del_location
          post :del_location

          get :list_locations
          post :list_locations

        end
      end

      resources :devices do
        collection do
          get :register_device
          post :register_device
          get :new_point_mobile
          post :new_point_mobile
          get :new_point
          post :new_point
          get :list_own_devices
          post :list_own_devices
          get :device_last_points
          post :device_last_points

          get :share_with
          post :share_with

          get :unshare
          post :unshare

        end

      end


    end
  end

end

app/controllers/api/v1/devices_controller.rb
class Api::V1::DevicesController < Api::V1::CommonController

  before_action :set_user, except: [:new_point]
  skip_before_filter :verify_authenticity_token



  def register_device
    if params[:imei].present? && params[:name].present? && params[:type_id]

      d =Device.new
      d.imei = params[:imei]
      d.name = params[:name]
      d.user_id = @user
      d.type_id = params[:type_id]
      d.active = true
      d.available = true
      if d.valid?
        d.save
        api_ok(:imei=>d.imei)


      else
        api_error(d.errors, 400)
      end
    else
      api_error("missing fields", 400)

    end


  end

  def new_point

    #########################
    ###                   ###
    ### no necesita token ###
    ###   es la llamada   ###
    ### desde java remoto ###
    ###                   ###
    #########################


    #solo dejarle si la api llama desde IP permitida

    #if ENV['ALLOWED_IP'].include? request.remote_ip
    if true
      if params[:imei].present? && params[:datetime].present? && params[:latitude].present? && params[:longitude].present? && params[:speed].present? && params[:altitude].present? && params[:course].present? && params[:extended].present?


        if Device.new_point(params[:imei], params[:datetime], params[:latitude], params[:longitude], params[:speed], params[:altitude], params[:course], params[:extended])
          api_ok(:imei=>params[:imei])

        else
          api_error("error", 500)
        end

      else
        api_error("missing fields", 400)
      end
    else
      api_error("?", 401)

    end


  end

  def new_point_mobile

    #ver si el user tiene ese device

    if params[:imei].present? && params[:datetime].present? && params[:latitude].present? && params[:longitude].present? && params[:speed].present? && params[:altitude].present? && params[:course].present? && params[:extended].present?
      if imei_belongs_to_user?(params[:imei], @user )
        if Device.new_point(params[:imei], params[:datetime], params[:latitude], params[:longitude], params[:speed], params[:altitude], params[:course], params[:extended])
          api_ok(:imei=>params[:imei])

        else
          api_error("error", 500)
        end
      else
        api_error("Device not yours", 401)
      end

    else
      api_error("missing fields", 400)
    end
  end

  def device_last_points_by_interval

    if params[:end_time].present?
      end_time = DateTime.strptime(params[:end_time].to_s,'%s').strftime("%y%m%d%H")
      end_timestamp = params[:end_time].to_f

    else
      end_time = 0
    end

    if params[:start_time].present? && params[:imei].present?
      imei = params[:imei]
      #paso todo formato yymmddhh
      start_time = DateTime.strptime(params[:start_time].to_s,'%s').strftime("%y%m%d%H")
      start_timestamp = params[:start_time].to_f

      Device.hours_with_points(imei)


    else
      api_error("Missing params", 401)
    end

  end

  def device_last_points

    #recibe imei y cintidad de puntos

    if params[:points].present? && params[:imei].present?

      points_quantity = params[:points].to_i
      imei = params[:imei]

      if imei_belongs_to_user?(imei, @user) || imei_is_shared_to_user?(imei, @user)

        device =  Hash.new

        p = $redis.hgetall(imei + ":d")
        device["device_id"]=p["dev"]

        device["imei"] = imei

        device["lat"]=p["lat"].present? ? p["lat"] : nil
        device["lon"]=p["lon"].present? ? p["lon"] : nil
        device["tim"]=p["tim"].present? ? p["tim"] : nil
        if points_quantity > 1
          device[:last_points] = Device.last_x_points(imei, points_quantity)

        end

        api_ok(:device=>device)
      else
        api_error("Device not yours", 401)
      end

    else
      api_error("Missing params", 401)
    end

  end


  def list_own_devices


      points_quantity = 0
      if params[:points].present?

        points_quantity = params[:points].to_i
      end
      devices=[]
      device =  Hash.new
      $redis.smembers("u:" + @user.to_s).each do |q|

        p = $redis.hgetall(q + ":d")
        device["device_id"]=p["dev"]

        device["imei"] = q
        device["own"] = 1
        device["alarms"] = 0

        device["name"]=p["name"].present? ? p["name"] : nil
        device["lat"]=p["lat"].present? ? p["lat"] : nil
        device["lon"]=p["lon"].present? ? p["lon"] : nil
        device["tim"]=p["tim"].present? ? p["tim"] : nil
        if points_quantity > 1
          device[:last_points] = Device.last_x_points(q, points_quantity)

        end

        devices.push device.clone
        device.clear

      end

      #esto me da los compartidos

      $redis.smembers("us:" + @user.to_s).each do |q|

        p = $redis.hgetall(q + ":d")
        device["device_id"]=p["dev"]

        device["imei"] = q

        device["own"] = 0

        device["alarms"] = 0

        device["name"]=p["name"].present? ? p["name"] : nil
        device["lat"]=p["lat"].present? ? p["lat"] : nil
        device["lon"]=p["lon"].present? ? p["lon"] : nil
        device["tim"]=p["tim"].present? ? p["tim"] : nil
        if points_quantity > 1
          device[:last_points] = Device.last_x_points(q, points_quantity)

        end

        devices.push device.clone
        device.clear

      end



      api_ok(:devices=>devices)


  end

  def share_with
    #recibo device_id y email o nick de con quien comparto


    if params[:imei].present? && params[:email].present?


      imei = params[:imei]
      user_shared  = User.where("email = ?",params[:email])

      if user_shared.present?
        user_shared = user_shared.first

      else
        api_error("Error user",200)
        return
      end
      if @user == user_shared.id.to_s
        api_error("share with yourself not allowed", 200)
        return
      end
      if imei_belongs_to_user?(imei, @user)

        #borro lo existente antes que sea igual





        Device.share_with(imei, @user, user_shared.id)

        api_ok("OK")

      else
        api_error("Not belongs to you", 200)
      end
    else
      api_error("Missing params",200)
    end


  end


  def unshare
    #recibo device_id y email o nick de con quien comparto


    if params[:imei].present? && params[:email].present?


      imei = params[:imei]
      user_shared  = User.where("email = ?",params[:email])

      if user_shared.present?
        user_shared = user_shared.first

      else
        api_error("Error user",200)
        return
      end
      if @user == user_shared.id.to_s
        api_error("share with yourself not allowed", 200)
        return
      end
      if imei_belongs_to_user?(imei, @user)

        #borro lo existente antes que sea igual

        Device.unshare(imei, @user, user_shared.id)

        api_ok("OK")

      else
        api_error("Not belongs to you", 200)
      end
    else
      api_error("Missing params",200)
    end


  end

end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy] #, :new_point, :new_point1]

  before_filter :authenticate_user!, :except => [:new_point, :new_point1]


  # GET /devices
  # GET /devices.json
  def index
    #@devices = Device.all

    @devices = Device.where("user_id = ?",current_user.id ).includes(:user)
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new




  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)
    @device.user = current_user


    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render action: 'show', status: :created, location: @device }

      else
        format.html { render action: 'new' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update

    #el imei NUNCA debe ser modificable.

    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy

    #$redis.srem("u:" + self.user.id.to_s, self.imei.to_s)
    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end

  def new_point

    if params[:imei].present? && params[:datetime].present? && params[:latitude].present? && params[:longitude].present? && params[:speed].present? && params[:altitude].present? && params[:course].present? && params[:extended].present?
       if Device.new_point(params[:imei], params[:datetime], params[:latitude], params[:longitude], params[:speed], params[:altitude], params[:course], params[:extended])
          render :text => ("OK")
        else
          render :text => ("KO")
       end
    else
      render :text => ("KO")
    end
  end


  def new_ack

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_device
    @device = Device.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def device_params
    params.require(:device).permit(:name, :user_id, :type_id, :last_lat, :last_lon, :last_fix, :active, :available, :imei)
  end
















end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>




    <% if @device.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

          <ul>
            <% @device.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <form action="php/contacts-process.php" method="post" id="widget-form" novalidate="novalidate">
      <div class="field"><%= f.text_field :name, :placeholder => "Nombre" %></div>
      <div class="field"><%= f.text_field :imei, :placeholder => "IMEI" %></div>

      <div class="field"><%= f.number_field  :type_id, :placeholder => "Tipo" %></div>

    <%= f.check_box :active, :placeholder => "Activo" %>
      <div class="field"><%= f.check_box :available, :placeholder => "Disponible" %></div>

       <div id="widget_server_responce"></div>
      <div class="buttons">
        <button type="reset">Reset</button><button type="submit">Grabar</button>
      </div>

    </form>



<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<div class="grid-col grid-col-9">
  <!-- cart products -->
  <div class="cart-products">
    <table>
      <tbody><tr>
        <th class="pic"></th>
        <th class="name">Product</th>
        <th class="price">Price</th>
        <th>Quantity</th>
        <th>Total</th>
        <th class="remove"></th>
      </tr>
      <tr>
        <td class="pic"><a href="#"><img src="pic/catalog-grid/item-2.jpg" width="54" height="54" alt=""></a></td>
        <td class="name"><h4><a href="#">Fujifilm Finepix xp50</a></h4></td>
        <td class="price">$900</td>
        <td class="quantity">
          <div><a href="#" class="minus"></a><input type="text" value="1"><a href="#" class="plus"></a></div>
        </td>
        <td class="price">$900</td>
        <td class="remove"><a href="#" class="fa fa-times"></a></td>
      </tr>
      <tr>
        <td class="pic"><a href="#"><img src="pic/catalog-grid/item-6.jpg" width="54" height="54" alt=""></a></td>
        <td class="name"><h4><a href="#">Motorola Triumph</a></h4></td>
        <td class="price">$5500</td>
        <td class="quantity">
          <div><a href="#" class="minus"></a><input type="text" value="1"><a href="#" class="plus"></a></div>
        </td>
        <td class="price">$5500</td>
        <td class="remove"><a href="#" class="fa fa-times"></a></td>
      </tr>
      <tr>
        <td colspan="6">
          <div class="coupon">
            <input type="text" placeholder="Coupon code">
            <button type="submit" class="button">Apply Coupon</button>
          </div>
          <button type="submit" class="button">Update Cart</button><!--
										--><button type="submit" class="button">Proceed to Checkout</button>
        </td>
      </tr>
      </tbody></table>
  </div>
  <!--/ cart products -->

  <!-- cart totals -->
  <div class="cart-totals">
    <h2>Cart Totals</h2>
    <table>
      <tbody><tr>
        <th>Cart Subtotal</th>
        <td>$6400</td>
      </tr>
      <tr>
        <th>Shipping and Handling</th>
        <td>Free Shipping</td>
      </tr>
      <tr>
        <th>Order Total</th>
        <td>$6400</td>
      </tr>
      </tbody></table>
  </div>
  <!--/ cart totals -->

  <!-- shipping calculator -->


  <!--/ shipping calculator -->
</div>


<h1>Listing devices</h1>

<table>
  <thead>
    <tr >
      <th>Name</th>
      <th>IMEI</th>
      <th>User</thv>
      <th>Type</th>
      <th>Last lat</th>
      <th>Last lon</th>
      <th>Last fix</th>
      <th>Active</th>
      <th >Available</th>
      <th ></th>
      <th ></th>
      <th> </th>
    </tr> </thead>

  <tbody>
    <% @devices.each do |device| %>
      <% p = Device.last_point(device.imei) %>
      <tr>
        <td><%= device.name %></td>
        <td><%= device.imei %></td>
        <td><%= device.user.name if device.user.present?%></td>
        <td><%= device.type_id %></td>
        <td><%= p[:lat] unless p.nil? %></td>
        <td><%= p[:lon] unless p.nil?%></td>
        <td><%= Device.last_fix(device.imei) %></td>
        <td><%= device.active %></td>
        <td><%= device.available %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<div class="grid-row">

  <div class="grid-col grid-col-6">
    <!-- feedback -->
    <div class="widget-alt widget-alt-feedback">
      <div class="head">New device</div>
      <div class="cont">
        <%= render 'form' %>
      </div>
    </div>
    <%= link_to 'Back', devices_path %>
  </div>
</div>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @device.user_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @device.type_id %>
</p>


<p>
  <strong>Active:</strong>
  <%= @device.active %>
</p>

<p>
  <strong>Available:</strong>
  <%= @device.available %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>