config/routes.rb
Lokusapp::Application.routes.draw do


  resources :devices do
    collection do
      get :new_point
      get :list_own_devices
    end


    member do

      get :new_point1
    end

  end

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  resources :home do


  end


  resources :faq do

  end

  resources :cart do

  end

  resources :item do

  end

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'loginpost'
        get 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end

      resources :users do
        collection do
          get :register_user
          post :register_user

        end
      end

      resources :locations do
        collection do
          get :add_location
          post :add_location

          get :del_location
          post :del_location

          get :list_locations
          post :list_locations

        end
      end

      resources :devices do
        collection do
          get :register_device
          post :register_device
          get :new_point_mobile
          post :new_point_mobile
          get :new_point
          post :new_point
          get :list_own_devices
          post :list_own_devices
          get :device_last_points
          post :device_last_points

          get :share_with
          post :share_with

          get :unshare
          post :unshare

        end

      end


    end
  end

end

app/views/layouts/web/_footer_bottom.erb
<footer class="page-footer-bottom">
  <div class="grid-row">
    <!-- secondary nav -->
    <nav class="secondary-nav">
      <ul>
        <li><a href="#">Home</a></li><!--
							--><li><a href="#">Features</a></li><!--
							--><li><a href="#">Pages</a></li><!--
							--><li><a href="#">Portfolio</a></li><!--
							--><li><a href="#">Blog</a></li><!--
							--><li><a href="#">Shop</a></li><!--
							--><li><a href="#">Contacts</a></li>
      </ul>
    </nav>
    <!--/ secondary nav -->

    <!-- copyrights -->
    <div class="copyrights">© 2014 - "the 8" Template. All rights reserved.</div>
    <!--/ copyrights -->
  </div>
</footer>

app/views/layouts/web/_footer_top.erb
<footer class="page-footer-top">
  <div class="grid-row">


    <div class="grid-col grid-col-4">
      <!-- contacts -->
      <div class="widget-alt widget-alt-contacts">
        <div class="head">Contact Info</div>
        <div class="cont">
          <address><i class="fa fa-map-marker"></i>Interdum et malesuada fames ac ante ipsum primis in faucibus malesuada.</address>
          <ul>
            <li><i class="fa fa-mobile"></i>(123) 456-7890</li>
            <li><i class="fa fa-mobile"></i>(123) 456-7891</li>
          </ul>
          <ul>
            <li><i class="fa fa-envelope-o"></i><a href="#">mail@mail.com</a></li>
            <li><i class="fa fa-link"></i><a href="#">www."the 8".com</a></li>
          </ul>
          <ol>
            <li><a href="#" class="fa fa-twitter"></a></li><!--
									--><li><a href="#" class="fa fa-facebook"></a></li><!--
									--><li><a href="#" class="fa fa-skype"></a></li><!--
									--><li><a href="#" class="fa fa-rss"></a></li><!--
									--><li><a href="#" class="fa fa-dribbble"></a></li>
          </ol>
        </div>
      </div>
      <!--/ contacts -->
    </div>

    <div class="grid-col grid-col-4">
      <!-- recent posts -->
      <div class="widget-alt widget-alt-posts">
        <div class="head">Recent Posts</div>
        <div class="cont">
          <ul>
            <li>
              <a href="#"><img src="/assets/pic/recent-posts/item-1.jpg" alt="item-1" width="58" height="58"></a>
              <p><a href="#">Etiam mi sapien, luctus ac tempor quis</a><i class="fa fa-angle-right"></i><span>October 16, 2014</span></p>
            </li>
            <li>
              <a href="#"><img src="/assets/pic/recent-posts/item-2.jpg" alt="item-1" width="58" height="58"></a>
              <p><a href="#">Etiam mi sapien, luctus ac tempor quis</a><i class="fa fa-angle-right"></i><span>October 12, 2014</span></p>
            </li>
            <li>
              <a href="#"><img src="/assets/pic/recent-posts/item-3.jpg" alt="item-1" width="58" height="58"></a>
              <p><a href="#">Etiam mi sapien, luctus ac tempor quis</a><i class="fa fa-angle-right"></i><span>October 10, 2014</span></p>
            </li>
          </ul>
        </div>
      </div>
      <!--/ recent posts -->
    </div>

    <div class="grid-col grid-col-4">
      <!-- feedback -->
      <div class="widget-alt widget-alt-feedback">
        <div class="head">Shoot a Message</div>
        <div class="cont">
          <form action="php/contacts-process.php" method="post" id="widget-form" novalidate="novalidate">
            <input type="text" name="name" placeholder="Name">
            <input type="email" name="email" placeholder="E-mail">
            <textarea cols="30" rows="5" name="message" placeholder="Message"></textarea>
            <div id="widget_server_responce"></div>
            <div class="buttons">
              <button type="reset">Reset</button><!--
										--><button type="submit">Send</button>
            </div>
          </form>
        </div>
      </div>
      <!--/ feedback -->
    </div>
  </div>
</footer>

app/views/layouts/web/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>

        <div class="grid-row">
          <div class="grid-col grid-col-12 composer">

            <div class="message">
              <i class="fa fa-info"></i>
              <h4><%= msg %></h4>

            </div>

            <br>

          </div>

        </div>

      <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/web/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>

      <% if current_user.present?  %>

        <%= link_to "Logout " + "estás logado como " + current_user.name  , '/users/sign_out', class: 'navbar-brand' %>
      <% else %>
          <%= link_to 'Log in', new_user_session_path, class: 'navbar-brand' %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/web/_navigation_bottom.erb
<header id="page-header-bottom" class="page-header-bottom">
  <div class="grid-row">
    <!-- logo -->
    <a href="/" class="logo">
      <img src="/assets/img/logo.png" alt="">
    </a>
    <!--/ logo -->

    <!-- main nav -->
    <nav class="main-nav">
      <ul>
        <li>
          <a href="/" class= <%= params[:controller] == "home" ? "active": "" %>><span class="fa fa-home"></span> Inicio</a>

        </li>
        <li>
          <a href="#"><span class="fa fa-map-marker"></span> Localizadores</a>
          <ul>
            <li><a href="woo-ready.html"><span class="fa fa-phone"></span> App. movil</a></li>
            <li><a href="woo-ready.html"><span class="fa fa-car"></span> Para coche</a></li>
            <li><a href="woo-ready.html"><span class="fa fa-bicycle"></span> Para motocicleta</a></li>
            <li><a href="woo-ready.html"><span class="fa fa-users"></span> Para personas</a></li>
            <li><a href="woo-ready.html"><span class="fa fa-refresh"></span> Portátiles</a></li>

          </ul>
        </li>
        <li>
          <%= link_to "F.A.Q.", faq_index_path, :class => params[:controller] == "faq" ? "active": ""   %>

        </li>

        <li>
          <a href="#">Blog</a>
          <ul>
            <li><a href="blog.html">Regular view</a></li>
            <li><a href="blog-three.html">Three columns</a></li>
            <li><a href="blog-two.html">Two columns</a></li>
            <li><a href="blog-one.html">One column</a></li>
            <li><a href="blog-single.html">Single post</a></li>
          </ul>
        </li>
        <li>
          <%= link_to "Catalog", item_index_path   %>
          <ul>
            <li><%= link_to "Catalog", item_index_path   %></li>
            <li><%= link_to "Cart",  cart_index_path  %></li>

          </ul>
        </li>
        <li>
          <a href="contacts.html">Contacto</a>
        </li>
      </ul>
    </nav>
    <!--/ main nav -->

    <!-- mobile nav -->
    <nav id="mobile-nav" class="mobile-nav">
      <a href="#mobile-nav-1" class="switcher"><i class="fa fa-align-justify"></i></a>
      <ul id="mobile-nav-1">
        <li><a href="#mobile-nav-7" class="opener active"><i class="fa fa-angle-right"></i><span class="fa fa-home"></span> Inicio</a></li>
        <li><a href="#mobile-nav-2" class="opener"><i class="fa fa-angle-right"></i>Features</a></li>
        <li><a href="#mobile-nav-3" class="opener"><i class="fa fa-angle-right"></i>Pages</a></li>
        <li><a href="#mobile-nav-4" class="opener"><i class="fa fa-angle-right"></i>Portfolio</a></li>
        <li><a href="#mobile-nav-5" class="opener"><i class="fa fa-angle-right"></i>Blog</a></li>
        <li><a href="#mobile-nav-6" class="opener"><i class="fa fa-angle-right"></i>Shop</a></li>
        <li><a href="contacts.html">Contacts</a></li>
      </ul>
      <ul id="mobile-nav-7">
        <li><a href="#mobile-nav-1" class="back"><em>←</em> &nbsp;BACK</a></li>
        <li><a href="index.html" class="active">Default Style</a></li>
        <li><a href="index-blog.html">Blog Style</a></li>
        <li><a href="index-parallax.html">Parallax Style</a></li>
        <li><a href="index-video.html">Background Video</a></li>
      </ul>
      <ul id="mobile-nav-2">
        <li><a href="#mobile-nav-1" class="back"><em>←</em> &nbsp;BACK</a></li>
        <li><a href="iOS8-inspired.html">iOS8 Inspired Design</a></li>
        <li><a href="woo-ready.html">Woo-Ready</a></li>
        <li><a href="#mobile-nav-8" class="opener"><i class="fa fa-angle-right"></i>Content Elements</a></li>
      </ul>
      <ul id="mobile-nav-8">
        <li><a href="#mobile-nav-2" class="back"><em>←</em> &nbsp;BACK</a></li>
        <li><a href="feature-accordion.html">Accordion</a></li>
        <li><a href="feature-buttons.html">Buttons</a></li>
        <li><a href="feature-callout.html">Callout</a></li>
        <li><a href="feature-chart-graph.html">Chart Graph</a></li>
        <li><a href="feature-chart-pie.html">Chart Pie</a></li>
        <li><a href="feature-chart-circle.html">Chart Circle</a></li>
        <li><a href="feature-columns.html">Columns</a></li>
        <li><a href="feature-dividers.html">Dividers</a></li>
        <li><a href="feature-icons.html">Icons</a></li>
        <li><a href="feature-lists.html">Lists</a></li>
        <li><a href="feature-messages.html">Messages</a></li>
        <li><a href="feature-milestone.html">Milestone</a></li>
        <li><a href="feature-pricing-table.html">Pricing Table</a></li>
        <li><a href="feature-progress-bar.html">Progress Bar</a></li>
        <li><a href="feature-services.html">Services</a></li>
        <li><a href="feature-tabs.html">Tabs</a></li>
        <li><a href="feature-team.html">Team</a></li>
        <li><a href="feature-testimonials.html">Testimonials</a></li>
        <li><a href="feature-toggle.html">Toggle</a></li>
        <li><a href="feature-twitter.html">Twitter</a></li>
        <li><a href="feature-twitter-carousel.html">Twitter Carousel</a></li>
        <li><a href="feature-video.html">Video</a></li>
      </ul>
      <ul id="mobile-nav-3">
        <li><a href="#mobile-nav-1" class="back"><em>←</em> &nbsp;BACK</a></li>
        <li><a href="page-404.html">404 page</a></li>
        <li><a href="page-about.html">About us</a></li>
        <li><a href="page-coming.html">Coming soon</a></li>
        <li><a href="page-faq.html">FAQ</a></li>
        <li><a href="page-team.html">Our team</a></li>
        <li><a href="page-process.html">Our process</a></li>
        <li><a href="page-progress.html">Our progress</a></li>
        <li><a href="page-services.html">Our services</a></li>
        <li><a href="page-sitemap.html">Sitemap</a></li>
        <li><a href="page-sidebar-one.html">With one sidebar</a></li>
        <li><a href="page-sidebar-two.html">With two sidebars</a></li>
        <li><a href="page-sidebar-none.html">Full width</a></li>
      </ul>
      <ul id="mobile-nav-4">
        <li><a href="#mobile-nav-1" class="back"><em>←</em> &nbsp;BACK</a></li>
        <li><a href="portfolio-four.html">Four columns</a></li>
        <li><a href="portfolio-three.html">Three columns</a></li>
        <li><a href="portfolio-two.html">Two columns</a></li>
        <li><a href="portfolio-one.html">One column</a></li>
        <li><a href="portfolio-gallery.html">Gallery</a></li>
        <li><a href="portfolio-single.html">Single item</a></li>
      </ul>
      <ul id="mobile-nav-5">
        <li><a href="#mobile-nav-1" class="back"><em>←</em> &nbsp;BACK</a></li>
        <li><a href="blog.html">Regular view</a></li>
        <li><a href="blog-three.html">Three columns</a></li>
        <li><a href="blog-two.html">Two columns</a></li>
        <li><a href="blog-one.html">One column</a></li>
        <li><a href="blog-single.html">Single post</a></li>
      </ul>
      <ul id="mobile-nav-6">
        <li><a href="#mobile-nav-1" class="back"><em>←</em> &nbsp;BACK</a></li>
        <li><%= link_to "Catalog", item_index_path   %></li>
        <li><%= link_to "Cart",  cart_index_path  %>></li>

      </ul>
    </nav>
    <!--/ main nav -->
  </div>
</header>

app/views/layouts/web/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/web/_navigation_top.erb
<header class="page-header-top">
  <div class="grid-row">
    <div class="row">
      <!-- language selector -->
      <div class="language-selector">
        <i class="fa fa-globe"></i>
        <span>Idioma:</span>
        <div>
          <a href="#">Castellano<i class="fa fa-angle-down"></i></a>
          <ul>
            <li><a href="#">English</a></li>
          </ul>
        </div>
      </div>
      <!--/ language selector -->
    </div>

    <div class="row">
      <!-- cart summary -->
      <div class="cart-summary">
        <i class="fa fa-shopping-cart"></i>
        <span>My cart:</span>
        <div>
          <a href="#">0 items<i class="fa fa-angle-down"></i></a>
          <ul>
            <li>

              <a href="#"><img src="/assets/pic/catalog-grid/item-2.jpg" width="54" height="54" alt=""></a>
              <h4><a href="#">Fujifilm Finepix xp50</a></h4>
              <p>1 × $900</p>
            </li>
            <li>
              <a href="#"><img src="/assets/pic/catalog-grid/item-6.jpg" width="54" height="54" alt=""></a>
              <h4><a href="#">Motorola Triumph</a></h4>
              <p>1 × $5500</p>
            </li>
            <li class="subtotal">Subtotal: $6400.00</li>
            <li class="total">
              <a href="#"><i class="fa fa-shopping-cart"></i>&nbsp; View Cart</a>
              <a href="#">Checkout &nbsp;<i class="fa fa-share"></i></a>
            </li>
          </ul>
        </div>
      </div>
      <!--/ cart summary -->
    </div>



    <% if current_user.present? %>
        <div class="row">
          <div class="cart-summary-right">
            <i class="fa fa-share"></i>
            <span><%= link_to "Log out", destroy_user_session_path %></span>

          </div>
        </div>
    <% end %>

    <div class="row">
      <!-- follow us -->
      <div class="cart-summary-right">

        <% unless current_user.present? %>
            <i class="fa fa-key"></i>
            <span><%= link_to "Log in", new_user_session_path %></span>
        <% else %>
            <i class="fa  fa-meh-o"></i>
            <span>Hola, <%= current_user.name %></span>
        <% end %>
      </div>




      <!--/ follow us -->
    </div>

    <a href="#" id="page-header-top-switcher" class="switcher"></a>
  </div>
</header>

app/views/layouts/web/_title.erb
<div class="page-title">
  <div class="grid-row">
    <h1><i class="fa fa-angle-right"></i>iOS8 Inspired Design</h1>
    <nav class="bread-crumbs">
      <a href="#">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;
      <a href="#">Features</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;
      <span>iOS8 Inspired Design</span>
    </nav>
  </div>
</div>

app/views/layouts/web/application.html.erb
<!DOCTYPE html>
<html>


<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Lokusapp" %></title>
<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Lokusapp" %>">
<%#= stylesheet_link_tag 'web/application', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'web/styles' %>
<%#= stylesheet_link_tag 'web/font-awesome' %>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<%= stylesheet_link_tag 'web/jquery.fancybox' %>
<%= stylesheet_link_tag 'web/owl.carousel' %>
<%= stylesheet_link_tag 'web/animate' %>

<%= csrf_meta_tags %>
</head>
<body>
<div class="page">
  <header>

    <%= render 'layouts/web/navigation_top' %>
    <%= render 'layouts/web/navigation_bottom' %>
    <%= render 'layouts/web/messages' %>


    <div id="page-header-bottom-holder" class="page-header-bottom-holder"></div>


  </header>


  <main role="main">
    <%= render 'layouts/web/title' %>
    <main class="page-content">
      <%= yield %>
    </main>

  </main>
  <%= render 'layouts/web/footer_top' %>
  <%= render 'layouts/web/footer_bottom' %>

</div>

<%= javascript_include_tag 'application' %>

</body>
</html>